
services:
  - type: web
    plan: free
    name: phishing2024
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn phishing2024.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"