# Generated by Django 5.1.3 on 2024-12-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_externa', models.URLField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
